### ISSUE TITLE
NPE - GetComponentName in .NET Android project

### ISSUE THREAD

**Issue by tuyen-vuduc** [DriveSmart-MobileTeam/dstracker_integration_sample#1]
I am facing this issue when trying to integrate the SDK to my .NET Android app.

Can you check how it can be happened?

## Error
```
[MonoDroid] Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ComponentName android.content.Intent.getComponent()' on a null object reference
[MonoDroid] 	at android.app.TaskStackBuilder.addNextIntentWithParentStack(TaskStackBuilder.java:107)
[MonoDroid] 	at com.dstracker.utils.Notifications$Companion.createNotification$tracker_release(Notifications.kt:59)
[MonoDroid] 	at com.dstracker.services.DSRecordingTripService.startForeground(DSRecordingTripService.kt:417)
[MonoDroid] 	at com.dstracker.services.DSRecordingTripService.onCreate(DSRecordingTripService.kt:127)
[MonoDroid] 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5073)
```

## Steps
1. Pull [the code](https://github.com/tuyen-vuduc/dotnet-drivesmart-quickstart) and configure as per readme file
2. Run the app from Visual Studio
3. Enable the app location permissions as always
4. Start the tracker

## Sample source
[Here](https://github.com/tuyen-vuduc/dotnet-drivesmart-quickstart) is the sample source ported from this repo.

**Comment by tuyen-vuduc** [comment]
Any help here?
